from korbash_lib import Tikalka, Time, DataBase
data=DataBase()
Time.SetZeroTime()
Time.freez()
tk = Tikalka(simulate=True) #simulate=True
# print(tk.motZ.getCoord()[0])
print(tk.tg.ReadValue(DataB=data))
tk.FindZero(zapas=0)
print(tk.tg.ReadValue(DataB=data))
tk.SetT(0.5,0.01)
# print(tk.motZ.getCoord()[0])
print(tk.tg.ReadValue(tau=10,DataB=data))
tk.SetT(0.7,0.01)
# print(tk.motZ.getCoord()[0])
print(tk.tg.ReadValue(tau=10,DataB=data))
tk.FindZero(zapas=100)
print(tk.tg.ReadValue(tau=10,DataB=data))
# print(tk.motZ.coord)
# for i in range(1000):
#     print(tk.tg.ReadValue(DataB=DataBase()))
#     hag=input()
#     tk.motZ.move(hag)
#     print(tk.tg.ReadValue(tau=5, DataB=DataBase()))