from korbash_lib import Tikalka, Time, DataBase
data=DataBase()
Time.SetZeroTime()
Time.freez()
tk = Tikalka(simulate=True)
print(tk.motZ.getCoord()[0])
print(tk.tg.ReadValue(DataB=data))
tk.FindZero()
print(tk.motZ.getCoord()[0])
print(tk.tg.ReadValue(DataB=data))
tk.SetT(2,0.001)
print(tk.motZ.getCoord()[0])
print(tk.tg.ReadValue(DataB=data))
tk.SetT(1,0.001)
print(tk.motZ.getCoord()[0])
print(tk.tg.ReadValue(DataB=data))